package fr.paladium.palamod.modules.ajobs.common.registerer.quest;

import fr.paladium.palaforgeutils.lib.itemstack.ItemStackSerializer;
import fr.paladium.palajobs.api.type.JobType;
import fr.paladium.palajobs.api.type.QuestType;
import fr.paladium.palajobs.core.quest.types.ActionQuest;
import fr.paladium.palajobs.core.quest.types.BlockBreakQuest;
import fr.paladium.palajobs.core.quest.types.EntityFeedQuest;
import fr.paladium.palajobs.core.quest.types.EntityKillQuest;
import fr.paladium.palajobs.core.quest.types.FishingQuest;
import fr.paladium.palajobs.core.quest.types.FurnaceCraftQuest;
import fr.paladium.palajobs.core.quest.types.ItemCraftQuest;
import fr.paladium.palajobs.core.quest.types.ItemGiveQuest;
import fr.paladium.palamod.api.BlocksRegister;
import fr.paladium.palamod.api.ItemsRegister;
import fr.paladium.palamod.modules.hunter.entites.EntityTurtle;
import fr.paladium.palamod.modules.world.PWorld;
import fr.paladium.palaspawner.common.registry.SpawnerBlockRegistry;
import java.util.Base64;
import net.minecraft.block.Block;
import net.minecraft.entity.monster.EntityCreeper;
import net.minecraft.entity.monster.EntityPigZombie;
import net.minecraft.entity.passive.EntityChicken;
import net.minecraft.entity.passive.EntityCow;
import net.minecraft.entity.passive.EntityHorse;
import net.minecraft.entity.passive.EntityMooshroom;
import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;

public class QuestRegisterer {
  private static QuestRegisterer instance;
  
  public QuestRegisterer() {
    instance = this;
  }
  
  public void registerQuests() {
    BlockBreakQuest.builder()
      .id("blockbreak.log.1")
      .job(JobType.ALCHEMIST)
      .type(QuestType.BLOCK_BREAK)
      .name("Cueilleur d'écorce")
      .description("Casser 200 bûches de jacaranda")
      .icon(Base64.getEncoder().encodeToString(ItemStackSerializer.write(new ItemStack(PWorld.LOG_JACARANDA)).getBytes()).toString())
      .quantity(200)
      .earnedExperience(750.0D)
      .stack(new ItemStack(PWorld.LOG_JACARANDA))
      .build().register();
    BlockBreakQuest.builder()
      .id("blockbreak.log.2")
      .job(JobType.ALCHEMIST)
      .type(QuestType.BLOCK_BREAK)
      .name("Briseur d'écorce")
      .description("Casser 200 bûches de judeecercis")
      .icon(Base64.getEncoder().encodeToString(ItemStackSerializer.write(new ItemStack(PWorld.LOG_JUDEECERCIS)).getBytes()).toString())
      .quantity(200)
      .earnedExperience(750.0D)
      .stack(new ItemStack(PWorld.LOG_JUDEECERCIS))
      .build().register();
    BlockBreakQuest.builder()
      .id("blockbreak.log.3")
      .job(JobType.ALCHEMIST)
      .type(QuestType.BLOCK_BREAK)
      .name("Récolteur d'écorce")
      .description("Casser 200 bûches d'érable")
      .icon(Base64.getEncoder().encodeToString(ItemStackSerializer.write(new ItemStack(PWorld.LOG_ERABLE)).getBytes()).toString())
      .quantity(200)
      .earnedExperience(750.0D)
      .stack(new ItemStack(PWorld.LOG_ERABLE))
      .build().register();
    BlockBreakQuest.builder()
      .id("blockbreak.log.4")
      .job(JobType.ALCHEMIST)
      .type(QuestType.BLOCK_BREAK)
      .name("Collectionneur d'écorce")
      .description("Casser 200 bûches d'ostrya")
      .icon(Base64.getEncoder().encodeToString(ItemStackSerializer.write(new ItemStack(PWorld.LOG_OSTRYA)).getBytes()).toString())
      .quantity(200)
      .earnedExperience(750.0D)
      .stack(new ItemStack(PWorld.LOG_OSTRYA))
      .build().register();
    ItemGiveQuest.builder()
      .id("itemgive.awkward.potion")
      .job(JobType.ALCHEMIST)
      .type(QuestType.ITEM_GIVE)
      .name("Ma sorcière bien-aimée")
      .description("Donner 64 potions étranges")
      .icon(Base64.getEncoder().encodeToString(ItemStackSerializer.write(new ItemStack((Item)Items.field_151068_bn, 1, 16)).getBytes()).toString())
      .quantity(64)
      .earnedExperience(1000.0D)
      .stack(new ItemStack((Item)Items.field_151068_bn, 1, 16))
      .build().register();
    ItemGiveQuest.builder()
      .id("itemgive.brewingstand")
      .job(JobType.ALCHEMIST)
      .type(QuestType.ITEM_GIVE)
      .name("L'alchimiste fou")
      .description("Donner 15 alambics")
      .icon(Base64.getEncoder().encodeToString(ItemStackSerializer.write(new ItemStack(Items.field_151067_bt)).getBytes()).toString())
      .quantity(15)
      .earnedExperience(750.0D)
      .stack(new ItemStack(Items.field_151067_bt))
      .build().register();
    ItemGiveQuest.builder()
      .id("itemgive.poppy")
      .job(JobType.ALCHEMIST)
      .type(QuestType.ITEM_GIVE)
      .name("It's Poppy Time")
      .description("Donner 64 coquelicots")
      .icon(Base64.getEncoder().encodeToString(ItemStackSerializer.write(new ItemStack((Block)Blocks.field_150328_O)).getBytes()).toString())
      .quantity(64)
      .earnedExperience(500.0D)
      .stack(new ItemStack((Block)Blocks.field_150328_O))
      .build().register();
    ItemGiveQuest.builder()
      .id("itemgive.dandelion")
      .job(JobType.ALCHEMIST)
      .type(QuestType.ITEM_GIVE)
      .name("Dents de lion ?")
      .description("Donner 64 pissenlits")
      .icon(Base64.getEncoder().encodeToString(ItemStackSerializer.write(new ItemStack((Block)Blocks.field_150327_N)).getBytes()).toString())
      .quantity(64)
      .earnedExperience(500.0D)
      .stack(new ItemStack((Block)Blocks.field_150327_N))
      .build().register();
    ItemGiveQuest.builder()
      .id("itemgive.tallgrass")
      .job(JobType.ALCHEMIST)
      .type(QuestType.ITEM_GIVE)
      .name("Coup de machette tchic tchac")
      .description("Donner 512 fougères")
      .icon(Base64.getEncoder().encodeToString(ItemStackSerializer.write(new ItemStack((Block)Blocks.field_150329_H, 1, 2)).getBytes()).toString())
      .quantity(512)
      .earnedExperience(1000.0D)
      .stack(new ItemStack((Block)Blocks.field_150329_H, 1, 2))
      .build().register();
    ActionQuest.builder()
      .id("itemuse.potionlauncher")
      .job(JobType.ALCHEMIST)
      .type(QuestType.ACTION)
      .name("Pew pew pew")
      .description("Utiliser 10 fois un potion launcher")
      .icon(Base64.getEncoder().encodeToString(ItemStackSerializer.write(new ItemStack(ItemsRegister.POTION_LAUNCHER)).getBytes()).toString())
      .quantity(10)
      .earnedExperience(500.0D)
      .action("POTION_LAUNCHER")
      .build().register();
    ActionQuest.builder()
      .id("itemuse.xpberry")
      .job(JobType.ALCHEMIST)
      .type(QuestType.ACTION)
      .name("Yummi !")
      .description("Utiliser 32 baies d'XP")
      .icon(Base64.getEncoder().encodeToString(ItemStackSerializer.write(new ItemStack((Item)ItemsRegister.XP_BERRY)).getBytes()).toString())
      .quantity(32)
      .earnedExperience(500.0D)
      .action("USE_XPBERRY")
      .build().register();
    ItemCraftQuest.builder()
      .id("itemuse.stew")
      .job(JobType.ALCHEMIST)
      .type(QuestType.ITEM_CRAFT)
      .name("Good soup")
      .description("Crafter 16 soupes")
      .icon(Base64.getEncoder().encodeToString(ItemStackSerializer.write(new ItemStack(Items.field_151009_A)).getBytes()).toString())
      .quantity(16)
      .earnedExperience(1000.0D)
      .stack(new ItemStack(Items.field_151009_A))
      .build().register();
    ItemCraftQuest.builder()
      .id("itemcraft.deadplanks")
      .job(JobType.ALCHEMIST)
      .type(QuestType.ITEM_CRAFT)
      .name("Un parquet mortel")
      .description("Crafter 32 planches mortes")
      .icon(Base64.getEncoder().encodeToString(ItemStackSerializer.write(new ItemStack(BlocksRegister.PLANKS_DEAD_WOOD)).getBytes()).toString())
      .quantity(32)
      .earnedExperience(750.0D)
      .stack(new ItemStack(BlocksRegister.PLANKS_DEAD_WOOD))
      .build().register();
    ItemCraftQuest.builder()
      .id("itemcraft.flowerpot")
      .job(JobType.ALCHEMIST)
      .type(QuestType.ITEM_CRAFT)
      .name("Le potier")
      .description("Crafter 64 pots de fleurs")
      .icon(Base64.getEncoder().encodeToString(ItemStackSerializer.write(new ItemStack(Items.field_151162_bE)).getBytes()).toString())
      .quantity(64)
      .earnedExperience(1000.0D)
      .stack(new ItemStack(Items.field_151162_bE))
      .build().register();
    ActionQuest.builder()
      .id("itemuse.hoe")
      .job(JobType.FARMER)
      .type(QuestType.ACTION)
      .name("Bêcheur infatigable")
      .description("Bêcher 500 blocs de terre")
      .icon(Base64.getEncoder().encodeToString(ItemStackSerializer.write(new ItemStack(Items.field_151012_L)).getBytes()).toString())
      .quantity(500)
      .earnedExperience(1000.0D)
      .action("USE_HOE")
      .build().register();
    ActionQuest.builder()
      .id("itemuse.bonemeal")
      .job(JobType.FARMER)
      .type(QuestType.ACTION)
      .name("Engrais rapide")
      .description("Utiliser 256 poudres d'os")
      .icon(Base64.getEncoder().encodeToString(ItemStackSerializer.write(new ItemStack(Items.field_151100_aR, 1, 15)).getBytes()).toString())
      .quantity(256)
      .earnedExperience(1000.0D)
      .action("USE_BONEMEAL")
      .build().register();
    ActionQuest.builder()
      .id("itemuse.cookies")
      .job(JobType.FARMER)
      .type(QuestType.ACTION)
      .name("Des petits cookies")
      .description("Manger 10 cookies")
      .icon(Base64.getEncoder().encodeToString(ItemStackSerializer.write(new ItemStack(Items.field_151106_aX)).getBytes()).toString())
      .quantity(10)
      .earnedExperience(500.0D)
      .action("EAT_COOKIE")
      .build().register();
    ItemGiveQuest.builder()
      .id("itemgive.milkextract")
      .job(JobType.FARMER)
      .type(QuestType.ITEM_GIVE)
      .name("Du lait bien frais")
      .description("Donner 20 sceaux de lait fraichement récupérés")
      .icon(Base64.getEncoder().encodeToString(ItemStackSerializer.write(new ItemStack(Items.field_151117_aB)).getBytes()).toString())
      .quantity(20)
      .earnedExperience(750.0D)
      .stack(new ItemStack(Items.field_151117_aB))
      .build().register();
    ItemCraftQuest.builder()
      .id("craft.hayblock")
      .job(JobType.FARMER)
      .type(QuestType.ITEM_CRAFT)
      .name("Un fermier, un vrai")
      .description("Crafter 64 bottes de paille")
      .icon(Base64.getEncoder().encodeToString(ItemStackSerializer.write(new ItemStack(Blocks.field_150407_cf)).getBytes()).toString())
      .quantity(64)
      .earnedExperience(750.0D)
      .stack(new ItemStack(Blocks.field_150407_cf))
      .build().register();
    ItemCraftQuest.builder()
      .id("craft.paper")
      .job(JobType.FARMER)
      .type(QuestType.ITEM_CRAFT)
      .name("Le bibliothéquaire")
      .description("Crafter 99 papiers")
      .icon(Base64.getEncoder().encodeToString(ItemStackSerializer.write(new ItemStack(Items.field_151121_aF)).getBytes()).toString())
      .quantity(99)
      .earnedExperience(500.0D)
      .stack(new ItemStack(Items.field_151121_aF))
      .build().register();
    EntityFeedQuest.builder()
      .id("feed.chicken")
      .job(JobType.FARMER)
      .type(QuestType.ENTITY_FEED)
      .name("Un éleveur aux petits soins")
      .description("Nourrir 20 poules")
      .icon(Base64.getEncoder().encodeToString(ItemStackSerializer.write(new ItemStack(Items.field_151014_N)).getBytes()).toString())
      .quantity(20)
      .earnedExperience(750.0D)
      .entityType(EntityChicken.class)
      .build().register();
    EntityFeedQuest.builder()
      .id("feed.cow")
      .job(JobType.FARMER)
      .type(QuestType.ENTITY_FEED)
      .name("Boeuf de qualité")
      .description("Nourrir 20 vaches")
      .icon(Base64.getEncoder().encodeToString(ItemStackSerializer.write(new ItemStack(Items.field_151015_O)).getBytes()).toString())
      .quantity(20)
      .earnedExperience(750.0D)
      .entityType(EntityCow.class)
      .build().register();
    BlockBreakQuest.builder()
      .id("blockbreak.cactus")
      .job(JobType.FARMER)
      .type(QuestType.BLOCK_BREAK)
      .name("Le monde entier est un cactus")
      .description("Casser 64 cactus")
      .icon(Base64.getEncoder().encodeToString(ItemStackSerializer.write(new ItemStack(Blocks.field_150434_aF)).getBytes()).toString())
      .quantity(64)
      .earnedExperience(750.0D)
      .stack(new ItemStack(Blocks.field_150434_aF))
      .build().register();
    BlockBreakQuest.builder()
      .id("blockbreak.melon")
      .job(JobType.FARMER)
      .type(QuestType.BLOCK_BREAK)
      .name("Steak ? Pastèque !")
      .description("Casser 32 pastèques")
      .icon(Base64.getEncoder().encodeToString(ItemStackSerializer.write(new ItemStack(Blocks.field_150440_ba)).getBytes()).toString())
      .quantity(32)
      .earnedExperience(500.0D)
      .stack(new ItemStack(Blocks.field_150440_ba))
      .build().register();
    ItemGiveQuest.builder()
      .id("itemgive.pumpkin")
      .job(JobType.FARMER)
      .type(QuestType.ITEM_GIVE)
      .name("Pala'tarte")
      .description("Donner 3 tartes à la citrouille")
      .icon(Base64.getEncoder().encodeToString(ItemStackSerializer.write(new ItemStack(Items.field_151158_bO)).getBytes()).toString())
      .quantity(3)
      .earnedExperience(750.0D)
      .stack(new ItemStack(Items.field_151158_bO))
      .build().register();
    ItemGiveQuest.builder()
      .id("itemgive.wheatseed")
      .job(JobType.FARMER)
      .type(QuestType.ITEM_GIVE)
      .name("Planter la petite graine")
      .description("Donner 256 graines de blé")
      .icon(Base64.getEncoder().encodeToString(ItemStackSerializer.write(new ItemStack(Items.field_151014_N)).getBytes()).toString())
      .quantity(256)
      .earnedExperience(500.0D)
      .stack(new ItemStack(Items.field_151014_N))
      .build().register();
    ItemGiveQuest.builder()
      .id("itemgive.poisonouspotato")
      .job(JobType.FARMER)
      .type(QuestType.ITEM_GIVE)
      .name("Les pommes, c'est has-been")
      .description("Donner 1 pomme de terre empoisonnée")
      .icon(Base64.getEncoder().encodeToString(ItemStackSerializer.write(new ItemStack(Items.field_151170_bI)).getBytes()).toString())
      .quantity(1)
      .earnedExperience(1000.0D)
      .stack(new ItemStack(Items.field_151170_bI))
      .build().register();
    EntityKillQuest.builder()
      .id("entitykill.creeper")
      .job(JobType.HUNTER)
      .type(QuestType.ENTITY_KILL)
      .name("Attention à pas faire boom")
      .description("Tuer 5 creepers")
      .icon(Base64.getEncoder().encodeToString(ItemStackSerializer.write(new ItemStack(ItemsRegister.PALADIUM_SWORD)).getBytes()).toString())
      .quantity(5)
      .earnedExperience(1000.0D)
      .entityType(EntityCreeper.class)
      .build().register();
    EntityKillQuest.builder()
      .id("entitykill.horses")
      .job(JobType.HUNTER)
      .type(QuestType.ENTITY_KILL)
      .name("Pour les lasagnes ?")
      .description("Tuer 25 chevaux")
      .icon(Base64.getEncoder().encodeToString(ItemStackSerializer.write(new ItemStack(ItemsRegister.PALADIUM_SWORD)).getBytes()).toString())
      .quantity(25)
      .earnedExperience(500.0D)
      .entityType(EntityHorse.class)
      .build().register();
    EntityKillQuest.builder()
      .id("entitykill.mushroomcow")
      .job(JobType.HUNTER)
      .type(QuestType.ENTITY_KILL)
      .name("Vache rouge")
      .description("Tuer 1 vache champignon")
      .icon(Base64.getEncoder().encodeToString(ItemStackSerializer.write(new ItemStack(Blocks.field_150419_aX)).getBytes()).toString())
      .quantity(1)
      .earnedExperience(500.0D)
      .entityType(EntityMooshroom.class)
      .build().register();
    EntityKillQuest.builder()
      .id("entitykill.pigmen")
      .job(JobType.HUNTER)
      .type(QuestType.ENTITY_KILL)
      .name("Zompigland")
      .description("Tuer 15 pigmen")
      .icon(Base64.getEncoder().encodeToString(ItemStackSerializer.write(new ItemStack(Items.field_151010_B)).getBytes()).toString())
      .quantity(15)
      .earnedExperience(500.0D)
      .entityType(EntityPigZombie.class)
      .build().register();
    EntityKillQuest.builder()
      .id("entitykill.turtle")
      .job(JobType.HUNTER)
      .type(QuestType.ENTITY_KILL)
      .name("Banni de l'île de la Tortue !")
      .description("Tuer 5 tortues")
      .icon(Base64.getEncoder().encodeToString(ItemStackSerializer.write(new ItemStack(ItemsRegister.PALADIUM_GREEN_SWORD)).getBytes()).toString())
      .quantity(5)
      .earnedExperience(750.0D)
      .entityType(EntityTurtle.class)
      .build().register();
    FurnaceCraftQuest.builder()
      .id("furnacecraft.steak")
      .job(JobType.HUNTER)
      .type(QuestType.FURNACE_CRAFT)
      .name("Comme d'hab Chef !")
      .description("Cuire 32 steaks")
      .icon(Base64.getEncoder().encodeToString(ItemStackSerializer.write(new ItemStack(Items.field_151083_be)).getBytes()).toString())
      .quantity(32)
      .earnedExperience(750.0D)
      .furnaceResult(new ItemStack(Items.field_151083_be))
      .build().register();
    ItemCraftQuest.builder()
      .id("craft.fermentedeye")
      .job(JobType.HUNTER)
      .type(QuestType.ITEM_CRAFT)
      .name("Oeil de 100 ans")
      .description("Crafter 10 yeux d'araignée fermentés")
      .icon(Base64.getEncoder().encodeToString(ItemStackSerializer.write(new ItemStack(Items.field_151071_bq)).getBytes()).toString())
      .quantity(10)
      .earnedExperience(1000.0D)
      .stack(new ItemStack(Items.field_151071_bq))
      .build().register();
    ItemCraftQuest.builder()
      .id("craft.paladiumsword")
      .job(JobType.HUNTER)
      .type(QuestType.ITEM_CRAFT)
      .name("Le forgeron")
      .description("Crafter une épée en paladium")
      .icon(Base64.getEncoder().encodeToString(ItemStackSerializer.write(new ItemStack(ItemsRegister.PALADIUM_SWORD)).getBytes()).toString())
      .quantity(1)
      .earnedExperience(500.0D)
      .stack(new ItemStack(ItemsRegister.PALADIUM_SWORD))
      .build().register();
    ItemGiveQuest.builder()
      .id("itemgive.rottenflesh")
      .job(JobType.HUNTER)
      .type(QuestType.ITEM_GIVE)
      .name("The Fleshing Dead")
      .description("Donner 128 chairs putréfiées")
      .icon(Base64.getEncoder().encodeToString(ItemStackSerializer.write(new ItemStack(Items.field_151078_bh)).getBytes()).toString())
      .quantity(128)
      .earnedExperience(500.0D)
      .stack(new ItemStack(Items.field_151078_bh))
      .build().register();
    FishingQuest.builder()
      .id("fishing.rawfish")
      .job(JobType.HUNTER)
      .type(QuestType.FISHING)
      .name("Miaou ! J'ai faim esclave !")
      .description("Pêcher 15 poissons")
      .icon(Base64.getEncoder().encodeToString(ItemStackSerializer.write(new ItemStack(Items.field_151115_aP, 1, 0)).getBytes()).toString())
      .quantity(15)
      .earnedExperience(1000.0D)
      .fish(new ItemStack(Items.field_151115_aP, 1, 0))
      .build().register();
    FishingQuest.builder()
      .id("fishing.salmon")
      .job(JobType.HUNTER)
      .type(QuestType.FISHING)
      .name("On va aller le fumer")
      .description("Pêcher 8 saumons")
      .icon(Base64.getEncoder().encodeToString(ItemStackSerializer.write(new ItemStack(Items.field_151115_aP, 1, 1)).getBytes()).toString())
      .quantity(8)
      .earnedExperience(1000.0D)
      .fish(new ItemStack(Items.field_151115_aP, 1, 1))
      .build().register();
    ActionQuest.builder()
      .id("itemuse.rottenflesh")
      .job(JobType.HUNTER)
      .type(QuestType.ACTION)
      .name("Survivaliste")
      .description("Manger 32 chairs putréfiées")
      .icon(Base64.getEncoder().encodeToString(ItemStackSerializer.write(new ItemStack(Items.field_151078_bh)).getBytes()).toString())
      .quantity(32)
      .earnedExperience(500.0D)
      .action("EAT_ROTTEN_FLESH")
      .build().register();
    ActionQuest.builder()
      .id("itemuse.bow")
      .job(JobType.HUNTER)
      .type(QuestType.ACTION)
      .name("Sniper")
      .description("Tirer 20 flèches avec un arc")
      .icon(Base64.getEncoder().encodeToString(ItemStackSerializer.write(new ItemStack((Item)Items.field_151031_f)).getBytes()).toString())
      .quantity(20)
      .earnedExperience(1000.0D)
      .action("ARROW_SHOT")
      .build().register();
    BlockBreakQuest.builder()
      .id("blockbreak.spawner")
      .job(JobType.HUNTER)
      .type(QuestType.BLOCK_BREAK)
      .name("Libérer les âmes")
      .description("Casser un spawner")
      .icon(Base64.getEncoder().encodeToString(ItemStackSerializer.write(new ItemStack(SpawnerBlockRegistry.EMPTY_MOB_SPAWNER)).getBytes()).toString())
      .quantity(1)
      .earnedExperience(1000.0D)
      .stack(new ItemStack(Blocks.field_150474_ac))
      .build().register();
    BlockBreakQuest.builder()
      .id("blockbreak.clay")
      .job(JobType.MINER)
      .type(QuestType.BLOCK_BREAK)
      .name("Atelier de poterie")
      .description("Miner 200 argiles")
      .icon(Base64.getEncoder().encodeToString(ItemStackSerializer.write(new ItemStack(Blocks.field_150435_aG)).getBytes()).toString())
      .quantity(200)
      .earnedExperience(500.0D)
      .stack(new ItemStack(Blocks.field_150435_aG))
      .build().register();
    BlockBreakQuest.builder()
      .id("blockbreak.greenpaladium")
      .job(JobType.MINER)
      .type(QuestType.BLOCK_BREAK)
      .name("GreenMining")
      .description("Miner 1 paladium vert")
      .icon(Base64.getEncoder().encodeToString(ItemStackSerializer.write(new ItemStack(PWorld.PALADIUM_GREEN_ORE)).getBytes()).toString())
      .quantity(1)
      .earnedExperience(1000.0D)
      .stack(new ItemStack(PWorld.PALADIUM_GREEN_ORE))
      .build().register();
    BlockBreakQuest.builder()
      .id("blockbreak.coalore")
      .job(JobType.MINER)
      .type(QuestType.BLOCK_BREAK)
      .name("Energie fossile")
      .description("Miner 128 minerais de charbon")
      .icon(Base64.getEncoder().encodeToString(ItemStackSerializer.write(new ItemStack(Blocks.field_150365_q)).getBytes()).toString())
      .quantity(128)
      .earnedExperience(1000.0D)
      .stack(new ItemStack(Blocks.field_150365_q))
      .build().register();
    BlockBreakQuest.builder()
      .id("blockbreak.diamondore")
      .job(JobType.MINER)
      .type(QuestType.BLOCK_BREAK)
      .name("Pierre préciseuse")
      .description("Miner 2 minerais de diamant")
      .icon(Base64.getEncoder().encodeToString(ItemStackSerializer.write(new ItemStack(Blocks.field_150482_ag)).getBytes()).toString())
      .quantity(2)
      .earnedExperience(1000.0D)
      .stack(new ItemStack(Blocks.field_150482_ag))
      .build().register();
    BlockBreakQuest.builder()
      .id("blockbreak.stone")
      .job(JobType.MINER)
      .type(QuestType.BLOCK_BREAK)
      .name("Le travail de la pierre")
      .description("Miner 5 000 pierres")
      .icon(Base64.getEncoder().encodeToString(ItemStackSerializer.write(new ItemStack(Blocks.field_150348_b)).getBytes()).toString())
      .quantity(5000)
      .earnedExperience(500.0D)
      .stack(new ItemStack(Blocks.field_150348_b))
      .build().register();
    BlockBreakQuest.builder()
      .id("blockbreak.quartz")
      .job(JobType.MINER)
      .type(QuestType.BLOCK_BREAK)
      .name("Le luxe à l'état pur")
      .description("Casser 64 minerais de quartz")
      .icon(Base64.getEncoder().encodeToString(ItemStackSerializer.write(new ItemStack(Blocks.field_150449_bY)).getBytes()).toString())
      .quantity(64)
      .earnedExperience(750.0D)
      .stack(new ItemStack(Blocks.field_150449_bY))
      .build().register();
    BlockBreakQuest.builder()
      .id("blockbreak.gravel")
      .job(JobType.MINER)
      .type(QuestType.BLOCK_BREAK)
      .name("Tombe en morceaux")
      .description("Miner 64 blocs de graviers")
      .icon(Base64.getEncoder().encodeToString(ItemStackSerializer.write(new ItemStack(Blocks.field_150351_n)).getBytes()).toString())
      .quantity(64)
      .earnedExperience(500.0D)
      .stack(new ItemStack(Blocks.field_150351_n))
      .build().register();
    FurnaceCraftQuest.builder()
      .id("blockbreak.coal")
      .job(JobType.MINER)
      .type(QuestType.FURNACE_CRAFT)
      .name("Energie bio")
      .description("Cuire 128 bois pour obtenir du charbon de bois")
      .icon(Base64.getEncoder().encodeToString(ItemStackSerializer.write(new ItemStack(Items.field_151044_h, 1, 1)).getBytes()).toString())
      .quantity(128)
      .earnedExperience(750.0D)
      .furnaceResult(new ItemStack(Items.field_151044_h, 1, 1))
      .build().register();
    FurnaceCraftQuest.builder()
      .id("blockbreak.netherbrick")
      .job(JobType.MINER)
      .type(QuestType.FURNACE_CRAFT)
      .name("Brique du nouveau monde ")
      .description("Cuire 256 briques du Nether")
      .icon(Base64.getEncoder().encodeToString(ItemStackSerializer.write(new ItemStack(Items.field_151130_bT)).getBytes()).toString())
      .quantity(256)
      .earnedExperience(500.0D)
      .furnaceResult(new ItemStack(Items.field_151130_bT))
      .build().register();
    FurnaceCraftQuest.builder()
      .id("blockbreak.ironore")
      .job(JobType.MINER)
      .type(QuestType.FURNACE_CRAFT)
      .name("Trône de fer")
      .description("Cuire 96 minerais de fer")
      .icon(Base64.getEncoder().encodeToString(ItemStackSerializer.write(new ItemStack(Items.field_151042_j)).getBytes()).toString())
      .quantity(96)
      .earnedExperience(750.0D)
      .furnaceResult(new ItemStack(Items.field_151042_j))
      .build().register();
    FurnaceCraftQuest.builder()
      .id("blockbreak.goldore")
      .job(JobType.MINER)
      .type(QuestType.FURNACE_CRAFT)
      .name("GoldenEye")
      .description("Cuire 10 minerais d'or")
      .icon(Base64.getEncoder().encodeToString(ItemStackSerializer.write(new ItemStack(Items.field_151043_k)).getBytes()).toString())
      .quantity(10)
      .earnedExperience(750.0D)
      .furnaceResult(new ItemStack(Items.field_151043_k))
      .build().register();
    ActionQuest.builder()
      .id("action.dynamite")
      .job(JobType.MINER)
      .type(QuestType.ACTION)
      .name("Creusage rapide")
      .description("Utiliser 10 dynamites")
      .icon(Base64.getEncoder().encodeToString(ItemStackSerializer.write(new ItemStack((Item)ItemsRegister.DYNAMITE)).getBytes()).toString())
      .quantity(10)
      .earnedExperience(750.0D)
      .action("DYNAMITE_USAGE")
      .build().register();
    ItemCraftQuest.builder()
      .id("craft.ironore")
      .job(JobType.MINER)
      .type(QuestType.ITEM_CRAFT)
      .name("Galerie des laves")
      .description("Crafter 2 éponges de lave")
      .icon(Base64.getEncoder().encodeToString(ItemStackSerializer.write(new ItemStack(BlocksRegister.LAVA_SPONGE)).getBytes()).toString())
      .quantity(2)
      .earnedExperience(1000.0D)
      .stack(new ItemStack(BlocksRegister.LAVA_SPONGE))
      .build().register();
  }
  
  public static QuestRegisterer getInstance() {
    if (instance == null)
      instance = new QuestRegisterer(); 
    return instance;
  }
}


/* Location:              E:\Paladium\!\fr\paladium\palamod\modules\ajobs\common\registerer\quest\QuestRegisterer.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.1.3
 */