package fr.paladium.palamod.modules.paladium.wiki;

import com.github.abrarsyed.secretroomsmod.common.SecretRooms;
import com.jaquadro.minecraft.storagedrawers.core.ModBlocks;
import com.jaquadro.minecraft.storagedrawers.core.ModItems;
import cpw.mods.ironchest.IronChest;
import fr.paladium.common.TooltipManager;
import fr.paladium.palamod.api.BlocksRegister;
import fr.paladium.palamod.api.ItemsRegister;
import fr.paladium.palamod.modules.pillage.registerer.PPRegisterer;
import fr.paladium.palamod.modules.world.PWorld;
import fr.welsymc.guardiangolem.common.init.ItemInit;
import net.minecraft.block.Block;
import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import noppes.npcs.CustomItems;

public class WikiRegister {
  public static void register() {
    TooltipManager.addWikiUrl(new ItemStack(CustomItems.carpentyBench), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-machines#11.-machines-de-bibliocraft");
    TooltipManager.addWikiUrl(new ItemStack(SecretRooms.camoPlateAll), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-ghost-blocks");
    TooltipManager.addWikiUrl(new ItemStack(SecretRooms.camoPlateHeavy), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-ghost-blocks");
    TooltipManager.addWikiUrl(new ItemStack(SecretRooms.camoPlateLight), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-ghost-blocks");
    TooltipManager.addWikiUrl(new ItemStack(SecretRooms.camoPlatePlayer), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-ghost-blocks");
    TooltipManager.addWikiUrl(new ItemStack(SecretRooms.solidAir), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-ghost-blocks");
    TooltipManager.addWikiUrl(new ItemStack(SecretRooms.camoGate), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-ghost-blocks");
    TooltipManager.addWikiUrl(new ItemStack(SecretRooms.camoGateExt), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-ghost-blocks");
    TooltipManager.addWikiUrl(new ItemStack(SecretRooms.torchLever), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-ghost-blocks");
    TooltipManager.addWikiUrl(new ItemStack(SecretRooms.camoTrapDoor), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-ghost-blocks");
    TooltipManager.addWikiUrl(new ItemStack(SecretRooms.camoLever), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-ghost-blocks");
    TooltipManager.addWikiUrl(new ItemStack(SecretRooms.camoButton), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-ghost-blocks");
    TooltipManager.addWikiUrl(new ItemStack(SecretRooms.oneWay), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-ghost-blocks");
    TooltipManager.addWikiUrl(new ItemStack(SecretRooms.camoLightDetector), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-ghost-blocks");
    TooltipManager.addWikiUrl(new ItemStack(SecretRooms.camoChest), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-stockages#6.-le-secret-chest");
    TooltipManager.addWikiUrl(new ItemStack(SecretRooms.camoStairs), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-ghost-blocks");
    TooltipManager.addWikiUrl(new ItemStack(SecretRooms.camoTrappedChest), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-ghost-blocks");
    TooltipManager.addWikiUrl(new ItemStack(SecretRooms.camoGhost), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-ghost-blocks");
    TooltipManager.addWikiUrl(new ItemStack(SecretRooms.camoDoorWoodItem), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-ghost-blocks");
    TooltipManager.addWikiUrl(new ItemStack(SecretRooms.camoDoorIronItem), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-ghost-blocks");
    TooltipManager.addWikiUrl(new ItemStack(SecretRooms.camoPaste), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-ghost-blocks");
    TooltipManager.addWikiUrl(new ItemStack(BlocksRegister.BLOCK_FINDIUM), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-minerais#4.-findium");
    TooltipManager.addWikiUrl(new ItemStack(BlocksRegister.BLOCK_TRIXIUM), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-minerais#7.-trixium");
    TooltipManager.addWikiUrl(new ItemStack(BlocksRegister.BLOCK_PALADIUM), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-minerais#3.-paladium");
    TooltipManager.addWikiUrl(new ItemStack(BlocksRegister.BLOCK_TITANE), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-minerais#2.-titane");
    TooltipManager.addWikiUrl(new ItemStack(BlocksRegister.BLOCK_AMETHYST), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-minerais#1.-amethyste");
    TooltipManager.addWikiUrl(new ItemStack(BlocksRegister.BLOCK_GPALADIUM), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-minerais#5.-paladium-vert");
    TooltipManager.addWikiUrl(new ItemStack((Block)BlocksRegister.PALADIUM_SLAB), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/pour-la-construction#4.-les-blocs-de-decoration-a-base-de-minerais");
    TooltipManager.addWikiUrl(new ItemStack((Block)BlocksRegister.PALADIUM_STAIRS), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/pour-la-construction#4.-les-blocs-de-decoration-a-base-de-minerais");
    TooltipManager.addWikiUrl(new ItemStack((Block)BlocksRegister.TITANE_SLAB), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/pour-la-construction#4.-les-blocs-de-decoration-a-base-de-minerais");
    TooltipManager.addWikiUrl(new ItemStack((Block)BlocksRegister.TITANE_STAIRS), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/pour-la-construction#4.-les-blocs-de-decoration-a-base-de-minerais");
    TooltipManager.addWikiUrl(new ItemStack((Block)BlocksRegister.AMETHYST_SLAB), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/pour-la-construction#4.-les-blocs-de-decoration-a-base-de-minerais");
    TooltipManager.addWikiUrl(new ItemStack((Block)BlocksRegister.AMETHYST_STAIRS), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/pour-la-construction#4.-les-blocs-de-decoration-a-base-de-minerais");
    TooltipManager.addWikiUrl(new ItemStack((Block)PWorld.SAPLING_JUDEECERCIS), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-ressources-naturelles#1.-les-plantes");
    TooltipManager.addWikiUrl(new ItemStack(PWorld.LOG_JUDEECERCIS), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-ressources-naturelles#2.-les-arbres");
    TooltipManager.addWikiUrl(new ItemStack(PWorld.LEAVE_JUDEECERCIS), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-ressources-naturelles#2.-les-arbres");
    TooltipManager.addWikiUrl(new ItemStack(PWorld.PLANKS_JUDEECERCIS), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-ressources-naturelles#2.-les-arbres");
    TooltipManager.addWikiUrl(new ItemStack((Block)PWorld.SAPLING_JACARANDA), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-ressources-naturelles#1.-les-plantes");
    TooltipManager.addWikiUrl(new ItemStack(PWorld.LOG_JACARANDA), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-ressources-naturelles#2.-les-arbres");
    TooltipManager.addWikiUrl(new ItemStack(PWorld.LEAVE_JACARANDA), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-ressources-naturelles#2.-les-arbres");
    TooltipManager.addWikiUrl(new ItemStack(PWorld.PLANKS_JACARANDA), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-ressources-naturelles#2.-les-arbres");
    TooltipManager.addWikiUrl(new ItemStack((Block)PWorld.SAPLING_ERABLE), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-ressources-naturelles#1.-les-plantes");
    TooltipManager.addWikiUrl(new ItemStack(PWorld.LOG_ERABLE), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-ressources-naturelles#2.-les-arbres");
    TooltipManager.addWikiUrl(new ItemStack(PWorld.LEAVE_ERABLE), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-ressources-naturelles#2.-les-arbres");
    TooltipManager.addWikiUrl(new ItemStack(PWorld.PLANKS_ERABLE), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-ressources-naturelles#2.-les-arbres");
    TooltipManager.addWikiUrl(new ItemStack((Block)PWorld.SAPLING_OSTRYA), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-ressources-naturelles#1.-les-plantes");
    TooltipManager.addWikiUrl(new ItemStack(PWorld.LOG_OSTRYA), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-ressources-naturelles#2.-les-arbres");
    TooltipManager.addWikiUrl(new ItemStack(PWorld.LEAVE_OSTRYA), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-ressources-naturelles#2.-les-arbres");
    TooltipManager.addWikiUrl(new ItemStack(PWorld.PLANKS_OSTRYA), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-ressources-naturelles#2.-les-arbres");
    TooltipManager.addWikiUrl(new ItemStack(BlocksRegister.DEAD_WOOD), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-ressources-naturelles#2.-les-arbres");
    TooltipManager.addWikiUrl(new ItemStack(BlocksRegister.PLANKS_DEAD_WOOD), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-ressources-naturelles#2.-les-arbres");
    TooltipManager.addWikiUrl(new ItemStack(PWorld.AMETHYST_ORE), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-minerais#1.-amethyste");
    TooltipManager.addWikiUrl(new ItemStack(PWorld.TITANE_ORE), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-minerais#2.-titane");
    TooltipManager.addWikiUrl(new ItemStack(PWorld.PALADIUM_ORE), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-minerais#3.-paladium");
    TooltipManager.addWikiUrl(new ItemStack(PWorld.PALADIUM_GREEN_ORE), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-minerais#5.-paladium-vert");
    TooltipManager.addWikiUrl(new ItemStack(PWorld.FINDIUM_ORE), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-minerais#4.-findium");
    TooltipManager.addWikiUrl(new ItemStack(PWorld.TRIXIUM_ORE), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-minerais#7.-trixium");
    TooltipManager.addWikiUrl(new ItemStack(BlocksRegister.ENDIUM_NUGGET_ORE), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-minerais#6.-endium");
    TooltipManager.addWikiUrl(new ItemStack(Blocks.field_150360_v), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/pour-le-pillage#4.-les-tnt-et-eponges");
    TooltipManager.addWikiUrl(new ItemStack(PPRegisterer.PPBlocks.COMPRESSED_SPONGE), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/pour-le-pillage#4.-les-tnt-et-eponges");
    TooltipManager.addWikiUrl(new ItemStack((Block)BlocksRegister.CAULDRON_BLOCK), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/autour-du-chaudron#1.-les-composants-du-chaudron");
    TooltipManager.addWikiUrl(new ItemStack((Block)BlocksRegister.CAULDRON_TANKSUPPORT), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/autour-du-chaudron#1.-les-composants-du-chaudron");
    TooltipManager.addWikiUrl(new ItemStack((Block)BlocksRegister.SHINY_JUDEECERCIS_WOOD), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/autour-du-chaudron#4.-les-portails");
    TooltipManager.addWikiUrl(new ItemStack((Block)BlocksRegister.SHINY_JACARANDA_WOOD), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/autour-du-chaudron#4.-les-portails");
    TooltipManager.addWikiUrl(new ItemStack((Block)BlocksRegister.SHINY_ERABLE_WOOD), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/autour-du-chaudron#4.-les-portails");
    TooltipManager.addWikiUrl(new ItemStack((Block)BlocksRegister.SHINY_OSTRYA_WOOD), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/autour-du-chaudron#4.-les-portails");
    TooltipManager.addWikiUrl(new ItemStack((Block)BlocksRegister.ENDIUM_ANGLE_PORTAL_BLOCK), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/autour-du-chaudron#4.-les-portails");
    TooltipManager.addWikiUrl(new ItemStack((Block)BlocksRegister.MYSTICAL_BOOKSHELF), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/autour-du-chaudron#2.-les-objets-divers");
    TooltipManager.addWikiUrl(new ItemStack(PPRegisterer.PPBlocks.EMPOWERED_QUARTZ), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-machines#9.-home-remover-et-coordinate-jammer");
    TooltipManager.addWikiUrl(new ItemStack(PPRegisterer.PPBlocks.COMPRESSED_QUARTZ), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-machines#9.-home-remover-et-coordinate-jammer");
    TooltipManager.addWikiUrl(new ItemStack(ItemsRegister.FRUIT_KIWANO), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-ressources-naturelles#3.-les-graines-et-fruits");
    TooltipManager.addWikiUrl(new ItemStack((Item)ItemsRegister.SEED_KIWANO), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-ressources-naturelles#3.-les-graines-et-fruits");
    TooltipManager.addWikiUrl(new ItemStack(ItemsRegister.FRUIT_ORANGEBLUE), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-ressources-naturelles#3.-les-graines-et-fruits");
    TooltipManager.addWikiUrl(new ItemStack((Item)ItemsRegister.SEED_ORANGEBLUE), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-ressources-naturelles#3.-les-graines-et-fruits");
    TooltipManager.addWikiUrl(new ItemStack(ItemsRegister.FRUIT_CHERVIL), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-ressources-naturelles#3.-les-graines-et-fruits");
    TooltipManager.addWikiUrl(new ItemStack((Item)ItemsRegister.SEED_CHERVIL), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-ressources-naturelles#3.-les-graines-et-fruits");
    TooltipManager.addWikiUrl(new ItemStack(ItemsRegister.FRUIT_EGGPLANT), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-ressources-naturelles#3.-les-graines-et-fruits");
    TooltipManager.addWikiUrl(new ItemStack((Item)ItemsRegister.SEED_EGGPLANT), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-ressources-naturelles#3.-les-graines-et-fruits");
    TooltipManager.addWikiUrl(new ItemStack(ItemsRegister.AMETHYST_INGOT), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-minerais#1.-amethyste");
    TooltipManager.addWikiUrl(new ItemStack(ItemsRegister.TITANE_INGOT), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-minerais#2.-titane");
    TooltipManager.addWikiUrl(new ItemStack(ItemsRegister.PALADIUM_INGOT), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-minerais#3.-paladium");
    TooltipManager.addWikiUrl(new ItemStack(ItemsRegister.PALADIUM_GREEN_INGOT), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-minerais#5.-paladium-vert");
    TooltipManager.addWikiUrl(new ItemStack(ItemsRegister.ENDIUM_INGOT), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-minerais#6.-endium");
    TooltipManager.addWikiUrl(new ItemStack(ItemsRegister.ENDIUM_FRAGMENT), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-minerais#6.-endium");
    TooltipManager.addWikiUrl(new ItemStack(ItemsRegister.FINDIUM), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-minerais#4.-findium");
    TooltipManager.addWikiUrl(new ItemStack(ItemsRegister.TRIXIUM), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-minerais#7.-trixium");
    TooltipManager.addWikiUrl(new ItemStack(ItemsRegister.ENDIUM_NUGGET), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-minerais#6.-endium");
    TooltipManager.addWikiUrl(new ItemStack(ItemsRegister.PARTICLE_IRON), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-ressources-naturelles#4.-les-particules");
    TooltipManager.addWikiUrl(new ItemStack(ItemsRegister.PARTICLE_GOLD), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-ressources-naturelles#4.-les-particules");
    TooltipManager.addWikiUrl(new ItemStack(ItemsRegister.PARTICLE_DIAMOND), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-ressources-naturelles#4.-les-particules");
    TooltipManager.addWikiUrl(new ItemStack(ItemsRegister.PARTICLE_AMETHYST), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-ressources-naturelles#4.-les-particules");
    TooltipManager.addWikiUrl(new ItemStack(ItemsRegister.PARTICLE_TITANE), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-ressources-naturelles#4.-les-particules");
    TooltipManager.addWikiUrl(new ItemStack(ItemsRegister.PARTICLE_PALADIUM), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-ressources-naturelles#4.-les-particules");
    TooltipManager.addWikiUrl(new ItemStack(ItemsRegister.FURNACE_UPGRADE), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-machines#13.-palafurnace");
    TooltipManager.addWikiUrl(new ItemStack(ItemsRegister.GOLDMIXEDCOAL), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-machines#6.-crusher");
    TooltipManager.addWikiUrl(new ItemStack(ItemsRegister.AMETHYSTMIXEDCOAL), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-machines#6.-crusher");
    TooltipManager.addWikiUrl(new ItemStack(ItemsRegister.TITANEMIXEDCOAL), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-machines#6.-crusher");
    TooltipManager.addWikiUrl(new ItemStack(ItemsRegister.PALAMIXEDCOAL), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-machines#6.-crusher");
    TooltipManager.addWikiUrl(new ItemStack(ItemsRegister.BOWUPGRADE_EMPTY), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-machines#3.-box-machine");
    TooltipManager.addWikiUrl(new ItemStack(ItemsRegister.COMPRESSED_AMETHYST), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/pour-les-crafts#3.-les-minerais-compresses");
    TooltipManager.addWikiUrl(new ItemStack(ItemsRegister.COMPRESSED_TITANE), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/pour-les-crafts#3.-les-minerais-compresses");
    TooltipManager.addWikiUrl(new ItemStack(ItemsRegister.COMPRESSED_PALADIUM), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/pour-les-crafts#3.-les-minerais-compresses");
    TooltipManager.addWikiUrl(new ItemStack(ItemsRegister.ORB_HEAL), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/pour-les-crafts#2.-les-orbes");
    TooltipManager.addWikiUrl(new ItemStack(ItemsRegister.ORB_JUMP), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/pour-les-crafts#2.-les-orbes");
    TooltipManager.addWikiUrl(new ItemStack(ItemsRegister.ORB_KNOCKBACK), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/pour-les-crafts#2.-les-orbes");
    TooltipManager.addWikiUrl(new ItemStack(ItemsRegister.ORB_SPEED), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/pour-les-crafts#2.-les-orbes");
    TooltipManager.addWikiUrl(new ItemStack(ItemsRegister.ORB_STRENGHT), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/pour-les-crafts#2.-les-orbes");
    TooltipManager.addWikiUrl(new ItemStack(ItemsRegister.STICK_AMETHYST), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/pour-les-crafts#1.-les-sticks");
    TooltipManager.addWikiUrl(new ItemStack(ItemsRegister.STICK_TITANE), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/pour-les-crafts#1.-les-sticks");
    TooltipManager.addWikiUrl(new ItemStack(ItemsRegister.STICK_PALADIUM), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/pour-les-crafts#1.-les-sticks");
    TooltipManager.addWikiUrl(new ItemStack(ItemsRegister.WITHER_SKULLFRAGMENT), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/pour-le-pillage#6.-objets-relatifs-au-wither");
    TooltipManager.addWikiUrl(new ItemStack(ItemsRegister.WITHER_DUST), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/pour-le-pillage#6.-objets-relatifs-au-wither");
    TooltipManager.addWikiUrl(new ItemStack(Items.field_151144_bL, 1, 1), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/pour-le-pillage#6.-objets-relatifs-au-wither");
    TooltipManager.addWikiUrl(new ItemStack(ItemsRegister.PALADIUM_CORE), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/pour-les-crafts#5.-autre");
    TooltipManager.addWikiUrl(new ItemStack(ItemsRegister.DIAMOND_STRING), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/pour-les-crafts#5.-autre");
    TooltipManager.addWikiUrl(new ItemStack(ItemsRegister.WING), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/pour-le-pvp#4.-autre");
    TooltipManager.addWikiUrl(new ItemStack(ItemsRegister.PLATE), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-machines#11.-machines-de-bibliocraft");
    TooltipManager.addWikiUrl(new ItemStack(ItemsRegister.PLATE_ENCHANTED), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-machines#11.-machines-de-bibliocraft");
    TooltipManager.addWikiUrl(new ItemStack(ItemsRegister.PALADIUM_INK), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-machines#11.-machines-de-bibliocraft");
    TooltipManager.addWikiUrl(new ItemStack((Item)ItemsRegister.GLUEBALL_PATTERN), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/autour-du-chaudron#2.-les-objets-divers");
    TooltipManager.addWikiUrl(new ItemStack((Item)ItemsRegister.ENDIUM_HEART), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/autour-du-chaudron#4.-les-portails");
    TooltipManager.addWikiUrl(new ItemStack(ItemsRegister.AMETHYST_POLLEN), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/autour-du-chaudron#5.-les-pollens");
    TooltipManager.addWikiUrl(new ItemStack(ItemsRegister.TITANE_POLLEN), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/autour-du-chaudron#5.-les-pollens");
    TooltipManager.addWikiUrl(new ItemStack(ItemsRegister.PALADIUM_POLLEN), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/autour-du-chaudron#5.-les-pollens");
    TooltipManager.addWikiUrl(new ItemStack(ItemsRegister.ENDIUM_POLLEN), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/autour-du-chaudron#5.-les-pollens");
    TooltipManager.addWikiUrl(new ItemStack(PPRegisterer.PPItems.AGRO_STONE), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/pour-le-pillage#6.-objets-relatifs-au-wither");
    TooltipManager.addWikiUrl(new ItemStack(PPRegisterer.PPItems.WITHER_SADDLE), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/pour-le-pillage#6.-objets-relatifs-au-wither");
    TooltipManager.addWikiUrl(new ItemStack(PPRegisterer.PPItems.WITHER_FISHINGROD), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/pour-le-pillage#6.-objets-relatifs-au-wither");
    TooltipManager.addWikiUrl(new ItemStack(ItemsRegister.GRAPPIN_HOOK), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-outils#11.-autre");
    TooltipManager.addWikiUrl(new ItemStack((Block)ModBlocks.compDrawers), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-stockages#4.-le-compacting-drawer-et-le-rangement-facile");
    TooltipManager.addWikiUrl(new ItemStack((Block)ModBlocks.controller), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-stockages#4.-le-compacting-drawer-et-le-rangement-facile");
    TooltipManager.addWikiUrl(new ItemStack((Block)ModBlocks.controllerSlave), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-stockages#4.-le-compacting-drawer-et-le-rangement-facile");
    TooltipManager.addWikiUrl(new ItemStack((Block)ModBlocks.framingTable), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-stockages#4.-le-compacting-drawer-et-le-rangement-facile");
    TooltipManager.addWikiUrl(new ItemStack((Block)ModBlocks.fullCustom1), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-stockages#3.-les-framed-drawers");
    TooltipManager.addWikiUrl(new ItemStack((Block)ModBlocks.fullCustom2), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-stockages#3.-les-framed-drawers");
    TooltipManager.addWikiUrl(new ItemStack((Block)ModBlocks.fullCustom4), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-stockages#3.-les-framed-drawers");
    TooltipManager.addWikiUrl(new ItemStack((Block)ModBlocks.fullDrawers1), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-stockages#3.-les-framed-drawers");
    TooltipManager.addWikiUrl(new ItemStack((Block)ModBlocks.fullDrawers2), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-stockages#3.-les-framed-drawers");
    TooltipManager.addWikiUrl(new ItemStack((Block)ModBlocks.fullDrawers4), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-stockages#3.-les-framed-drawers");
    TooltipManager.addWikiUrl(new ItemStack((Block)ModBlocks.halfCustom2), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-stockages#3.-les-framed-drawers");
    TooltipManager.addWikiUrl(new ItemStack((Block)ModBlocks.halfCustom4), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-stockages#3.-les-framed-drawers");
    TooltipManager.addWikiUrl(new ItemStack((Block)ModBlocks.halfDrawers2), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-stockages#3.-les-framed-drawers");
    TooltipManager.addWikiUrl(new ItemStack((Block)ModBlocks.halfDrawers4), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-stockages#3.-les-framed-drawers");
    TooltipManager.addWikiUrl(new ItemStack((Block)ModBlocks.trim), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-stockages#3.-les-framed-drawers");
    TooltipManager.addWikiUrl(new ItemStack((Block)ModBlocks.trimCustom), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-stockages#3.-les-framed-drawers");
    TooltipManager.addWikiUrl(new ItemStack((Item)ModItems.personalKey), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-stockages#5.-les-ameliorations-de-drawers");
    TooltipManager.addWikiUrl(new ItemStack((Item)ModItems.shroudKey), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-stockages#5.-les-ameliorations-de-drawers");
    TooltipManager.addWikiUrl(new ItemStack((Item)ModItems.upgrade), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-stockages#5.-les-ameliorations-de-drawers");
    TooltipManager.addWikiUrl(new ItemStack(ModItems.upgradeTemplate), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-stockages#5.-les-ameliorations-de-drawers");
    TooltipManager.addWikiUrl(new ItemStack((Item)ModItems.upgradeLock), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-stockages#5.-les-ameliorations-de-drawers");
    TooltipManager.addWikiUrl(new ItemStack((Item)ModItems.upgradeRedstone), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-stockages#5.-les-ameliorations-de-drawers");
    TooltipManager.addWikiUrl(new ItemStack((Item)ModItems.upgradeStatus), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-stockages#5.-les-ameliorations-de-drawers");
    TooltipManager.addWikiUrl(new ItemStack((Item)ModItems.upgradeVoid), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-stockages#5.-les-ameliorations-de-drawers");
    TooltipManager.addWikiUrl(new ItemStack(ItemInit.FOOD), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-machines#10.-machine-a-croquettes");
    TooltipManager.addWikiUrl(new ItemStack((Block)IronChest.ironChestBlock), "https://wiki.paladium-pvp.fr/items-et-machines/items-du-palamod/les-stockages#1.-les-coffres-moddes");
  }
}


/* Location:              E:\Paladium\!\fr\paladium\palamod\modules\paladium\wiki\WikiRegister.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.1.3
 */